fix compilation error in core_io.h
- error: 'vector' in namespace 'std' does not name a type
- add <vector> include in core_io.h
- remove <vector> includes from core_read.cpp and core_write.cpp

(cherry picked from commit 1b73d36b2c71c92044012dc736215bf95f2e908b)